title: <p align="center"> Camilo Villegas </p>

logo: "images/descarga.jpg"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/darlin-soto-v%C3%A1squez-b97469105/">LinkedIn</a> |
  <a href="https://github.com/DarlinSoto">GitHub</a>
  </p>
  
  <p align="justify">
Estudiante de Ingenieria Civil Electrica en Universidad de la Frontera, Chile.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
